/**
 * Design Review Handler
 *
 * Handles design review screenshots with Claude Vision API.
 */

import { promises as fs } from 'fs';
import { join } from 'path';
import Anthropic from '@anthropic-ai/sdk';
import {
  generateBaseFilename,
  truncateMessage,
  SCREENSHOT_DIR,
  MAX_LOG_MESSAGE_LENGTH,
} from '../../urlUtils.js';
import {
  getAnthropicClient,
  CLAUDE_MODEL,
  CLAUDE_MAX_TOKENS,
  CLAUDE_PRICING,
} from '../anthropic.js';
import { getProjectRoot } from '../index.js';

/** Design review prompt for Claude Vision */
export const DESIGN_REVIEW_PROMPT = `You are an expert UI/UX designer and frontend developer reviewing a web application screenshot.

Analyze this screenshot and provide a structured design review. Be specific, actionable, and prioritize the most impactful issues.

## Review Categories

### 1. Visual Bugs & Broken Elements
- Elements that appear cut off, overlapping incorrectly, or misaligned
- Broken layouts or obvious rendering issues
- Missing images or icons
- Text overflow or truncation problems

### 2. Design Inconsistencies
- Inconsistent spacing (margins, padding, gaps)
- Mismatched colors that break the visual hierarchy
- Typography inconsistencies (font sizes, weights, line heights)
- Border radius or shadow inconsistencies

### 3. Accessibility Concerns
- Low contrast text that may be hard to read
- Interactive elements that appear too small
- Missing visual focus indicators
- Color-only information conveyance

### 4. UI/UX Issues
- Confusing visual hierarchy
- Poor information density (too crowded or too sparse)
- Unclear interactive elements
- Navigation or wayfinding problems

### 5. Responsive Design Concerns
- Elements that may not scale well
- Fixed widths that could cause issues
- Content that may overflow on smaller screens

## Response Format

Provide your review in this markdown format:

# Design Review

## Summary
[1-2 sentence overview of the design quality and main concerns]

## Critical Issues
- [ ] [Issue description with specific location and fix recommendation]

## Improvements
- [ ] [Improvement suggestion with rationale]

## Positive Observations
- [What's working well in this design]

---
*Review generated by Sweetlink Design Review*

Be concise but specific. Reference element locations (e.g., "the header nav", "bottom-right card", "search input in toolbar").
If the screenshot shows a well-designed interface with no major issues, say so clearly.`;

export interface DesignReviewResult {
  screenshotPath: string;
  reviewPath: string;
}

/**
 * Handle design review screenshot: save screenshot, call Claude Vision API, save review markdown
 */
export async function handleDesignReviewScreenshot(data: {
  screenshot: string;
  logs?: Array<{ timestamp: number; level: string; message: string }>;
  url: string;
  timestamp: number;
  width: number;
  height: number;
}): Promise<DesignReviewResult> {
  const { screenshot, logs, url, timestamp, width, height } = data;

  // Create directory if it doesn't exist (relative to project root captured at server start)
  const dir = join(getProjectRoot(), SCREENSHOT_DIR);
  await fs.mkdir(dir, { recursive: true });

  // Generate filename with timestamp using shared utility
  const baseFilename = generateBaseFilename('design-review', timestamp);

  // Save screenshot (PNG for better quality in design review)
  const screenshotPath = join(dir, `${baseFilename}.png`);
  const base64Data = screenshot.replace(/^data:image\/(png|jpeg);base64,/, '');
  await fs.writeFile(screenshotPath, Buffer.from(base64Data, 'base64'));
  console.log(`[Sweetlink] Design review screenshot saved: ${screenshotPath}`);

  // Call Claude Vision API for design review
  console.log('[Sweetlink] Calling Claude Vision API for design review...');

  const client = getAnthropicClient();

  // Determine media type from data URL
  const mediaType = screenshot.startsWith('data:image/png') ? 'image/png' : 'image/jpeg';

  const response = await client.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: CLAUDE_MAX_TOKENS,
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'image',
            source: {
              type: 'base64',
              media_type: mediaType,
              data: base64Data,
            },
          },
          {
            type: 'text',
            text: DESIGN_REVIEW_PROMPT,
          },
        ],
      },
    ],
  });

  // Extract text content from response
  const reviewContent = response.content
    .filter((block): block is Anthropic.TextBlock => block.type === 'text')
    .map((block) => block.text)
    .join('\n\n');

  // Extract token usage and calculate cost
  const inputTokens = response.usage?.input_tokens ?? 0;
  const outputTokens = response.usage?.output_tokens ?? 0;
  const totalTokens = inputTokens + outputTokens;

  // Calculate costs using Claude pricing
  const inputCost = (inputTokens / 1_000_000) * CLAUDE_PRICING.input;
  const outputCost = (outputTokens / 1_000_000) * CLAUDE_PRICING.output;
  const totalCost = inputCost + outputCost;

  console.log(`[Sweetlink] Design review tokens: ${inputTokens} input, ${outputTokens} output, total: ${totalTokens}`);
  console.log(`[Sweetlink] Design review cost: $${totalCost.toFixed(4)}`);

  // Build the review markdown file
  const reviewMarkdown = `---
url: ${url}
timestamp: ${new Date(timestamp).toISOString()}
dimensions: ${width}x${height}
screenshot: ${baseFilename}.png
model: ${CLAUDE_MODEL}
tokens:
  input: ${inputTokens}
  output: ${outputTokens}
  total: ${totalTokens}
cost:
  input: $${inputCost.toFixed(4)}
  output: $${outputCost.toFixed(4)}
  total: $${totalCost.toFixed(4)}
---

${reviewContent}

---

## Console Logs Summary

${logs && logs.length > 0
    ? logs
        .filter((log) => log.level === 'error' || log.level === 'warn')
        .slice(0, 10)
        .map((log) => `- **${log.level.toUpperCase()}**: ${truncateMessage(log.message, MAX_LOG_MESSAGE_LENGTH)}`)
        .join('\n') || '_No errors or warnings in console_'
    : '_No console logs captured_'
}
`;

  // Save the review markdown
  const reviewPath = join(dir, `${baseFilename}.md`);
  await fs.writeFile(reviewPath, reviewMarkdown, 'utf-8');
  console.log(`[Sweetlink] Design review markdown saved: ${reviewPath}`);

  return { screenshotPath, reviewPath };
}
